name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  validate-blog:
    if: startsWith(github.head_ref, 'blog/') && !startsWith(github.head_ref, 'blog/admin/') && github.actor != 'github-actions[bot]' && github.actor != 'myciapp[bot]'
    # needs: [build, lint, typecheck]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
          cache: npm
      - run: npm ci
      - run: |
          git fetch origin main
          git diff origin/main..HEAD --name-only | xargs npm run validate-blog --

  update-blogmeta:
    if: github.actor != 'github-actions[bot]' && github.actor != 'myciapp[bot]'
    # needs: [validate-blog]
    permissions:
      contents: write
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        # Checkout pull request HEAD commit instead of merge commit
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
          cache: npm
      - run: npm ci
      - name: Update Blog Meta
        run: |
          git fetch origin main
          git diff origin/main..HEAD --name-status | xargs npm run update-blogmeta --
      - name: Generate GitHub App token
        id: generate
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.PRIVATE_KEY }}
      - name: Git Commit
        env:
          GITHUB_TOKEN: ${{ steps.generate.outputs.token }}
          GH_TOKEN: ${{ steps.generate.outputs.token }}
        run: |
          git add -N .
          if ! git diff --exit-code --quiet
          then
            git config --local user.email "740355+myciapp[bot]@users.noreply.github.com"
            git config --local user.name "myciapp[bot]"
            git add .
            git commit -m "[Bot] Update Blog Meta"
            git push
          fi
